services:
  #  accountsdb:
  #    container_name: accountsdb
  #    ports:
  #      - 3306:3306
  #    environment:
  #      MYSQL_DATABASE: accountsdb
  #    extends:
  #      file: common-config.yml
  #      service: microservice-db-config
  accounts:
    image: "suyashs52/accounts-service:v1"
    container_name: accounts-ms
    ports:
      - "8085:8085"
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      #      accountsdb:
      #        condition: service_healthy
      configserver:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    #      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "suyashs52/loan-service:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
#
#  loans_1:
#    image: "suyashs52/loan-service:v1"
#    container_name: loans-ms-1
#    ports:
#      - "8091:8090"
#    extends:
#      file: common-config.yml
#      service: microservice-eureka-config
#    depends_on:
#      eureka-server:
#        condition: service_healthy
#    environment:
#      SPRING_APPLICATION_NAME: "loans"

  cards:
    image: "suyashs52/card-service:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gateway-server:
    image: "suyashs52/gateway-server:v1"
    container_name: gateway-server-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
    extends:
      file: common-config.yml
      service: microservice-eureka-config




  configserver:
    image: "suyashs52/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"

    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


  eureka-server:
    image: "suyashs52/eureka-server:v1"
    container_name: eureka-server-ms
    ports:
      - "8070:8070"

    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"

networks:
  simple-bank:
    driver: "bridge"