# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: config-server-deployment
serviceName: config-server
appLabel: config-server
appName: config-server

replicaCount: 1

image:
  repository: suyashs52/configserver
  tag: v2

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

appname_enabled: true
profile_enabled: false
config_enabled: false
#eureka_enabled: false
discovery_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false