services:
  accounts:
    image: "suyashs52/accounts-service:v1"
    container_name: accounts-ms
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - simple-bank
  loans:
    image: "suyashs52/loan-service:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - simple-bank
  cards:
    image: "suyashs52/card-service:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - simple-bank
networks:
  simple-bank:
    driver: "bridge"