server:
  port: 8071
spring:
  application:
    name: "config-server"
  profiles:
    active: native
  #    active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
          #search-locations: "file:///Users//suyashkumarsingh//Downloads//microservice//bank-service//config-server//src//main//resources//config"
  #        git:
  #          uri: "https://github.com/eazybytes/eazybytes-config.git"
  #          default-label: main
  #          timeout: 5
  #          clone-on-start: true
  #          force-pull: true
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"